spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost # Change it with actual hostname in the production
    prefer-ip-address: false  # if you want to display ip address instead of hostname
  client:
    fetch-registry: false # Eureka server does not need to fetch registry information itself
    register-with-eureka: false # We don't need to register eureka server to eureka server
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # default url for eureka server
  server:
    enable-self-preservation: true # Protects registry during network partition
    eviction-internal-time-in-ms: 5000 # how often to evict dead instances (5s)
    renewal-percent-threshold: 0.85 # % of heartbeats needed to stay out of self-preservation

# Actuator endpoints
management:
  endpoints:
    web:
      exposures:
        include: health, info, refresh, busrefresh
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true

# We are using http protocol to communicate between eureka server and clients
# The eureka server will run on port 8761 (default eureka port)
server:
  port: 8761

# Info about the application
info:
  app:
    name: Eureka Server
    description: Service Discovery Server for Iconic Platform
    version: 1.0.0

